import { Nunito } from "next/font/google";
import "./globals.scss";
import "@/style/scss/app.scss"
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";


const nunito = Nunito({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={nunito.className}>
        <Header/>
        {children}
        <Footer/>
        <script src="https://api-maps.yandex.ru/v3/?apikey=YOUR_API_KEY&lang=ru_RU"></script>
      </body>

    </html>
  );
}
